name: GHAction example  

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'

jobs:
  ci_step:
    name: Build, tag and push Docker image to DockerHub
    runs-on: ubuntu-latest
      
    steps:
      - 
        name: Check out the source_repo
        uses: actions/checkout@v4
      
      -
        name: Docker metadata definitions
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKERHUB_USERNAME }}/example
          flavor: latest=false
          tags: |
            type=sha,priority=100,prefix=sha-,format=short
            type=semver,priority=200,pattern={{version}}   

      - 
        name: QEMU set-up
        uses: docker/setup-qemu-action@v3

      - 
        name: Buildx set-up
        uses: docker/setup-buildx-action@v3

      - 
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build image from dockerfile
        run: |
          docker build -t docker.io/kubaa1906/example:${{ github.sha }}
        
      - 
        name: Scan Docker image with Docker Scout
        id: docker-scout
        run: |
          docker scout cves ${{ vars.DOCKERHUB_USERNAME }}/example:${{ github.sha }} --exit-code 1 --only-severities critical,high

      -
        name: New tag of docker image
        if: steps.docker-scout.outcome == 'success'
        run: docker tag docker.io/kubaa1906/example:${{ github.sha }} docker.io/kubaa1906/example:success

      - 
        name: Push image to DockerHub
        if: steps.docker-scout.outcome == 'success'
        run: docker image push docker.io/kubaa1906/example:success
    
        
      